### ISSUE TITLE
Table of Contents missing some pages

### ISSUE THREAD

**Issue by seawolf42** [chalmerlowe/intro_to_sprinting#115]
Right now the TOC is missing at least a few pages that can be reached from the bottom navigation (for example, Pull Request Tips and Tricks is not referenced in the TOC).

**Comment by chalmerlowe** [comment]
@seawolf42 

Due to time pressure and such, we decided to bail on a number of things and so we quickly tried to trim off some pages that were incomplete, etc.

As it stands, the lessons that we offered on Sunday night were really close to 2 hours.

And to be honest, it felt about right. Will discuss more later.

**Comment by chalmerlowe** [comment]
Am thinking this might be a good project to do as part of a final clean up for a major release, since this will likely impact a number of other files across the board.

**Comment by seawolf42** [comment]
fixed by c0f288da16efb5be52011f2238899a3504366ea6
