### ISSUE TITLE
start with a clone

### ISSUE THREAD

**Issue by samsammurphy** [chalmerlowe/intro_to_sprinting#49]
It might be clearer to start with a clone rather than a fork..

We could perhaps then talk about setting the upstream as different from the origin THEN talk about making forks in github

**Comment by chalmerlowe** [comment]
Thanks for your suggestion. I appreciate the input.

Gonna close this. I can see some benefits, to the suggestion but for now, I think I wanna stick with the fork process as is.

Since this workshop is designed to prep folks for walking into a sprint and forking someone else's repo to get started on an open source project, I feel like the existing workflow will suffice for now.

chalmer

**Comment by samsammurphy** [comment]
Yep, agreed. I think it is better to start with a fork

(had written this comment live during the PyHawaii meetup, but on
reflection I see the light)

best,
Sam
